@baseUrl = http://localhost:3000
@postId = 1234567890abcdef12345678
@commentId = 1234567890abcdef12345678

### ===== AUTH REQUESTS ===== ###

### Register
POST {{baseUrl}}/api/auth/register
Content-Type: application/json

{
  "name": "Maya Klein",
  "email": "hey@example.com",
  "password": "123456"
}

###

### Login
POST {{baseUrl}}/api/auth/login
Content-Type: application/json

{
  "email": "maya@example.com",
  "password": "123456"
}

###

### ===== POSTS REQUESTS ===== ###

### Get All Posts (Default Paging - First Page, 10 per page)
GET {{baseUrl}}/api/posts

###

### Get Paginated Posts - Page 2, 10 Posts Per Page
GET {{baseUrl}}/api/posts?page=2&limit=10

###

### Get Paginated Posts - Page 3, 5 Posts Per Page
GET {{baseUrl}}/api/posts?page=3&limit=5

###

### Get Post by ID
GET {{baseUrl}}/api/posts/{{postId}}

###

### ===== COMMENTS REQUESTS ===== ###

### Get All Comments
GET {{baseUrl}}/api/comments

###

### Get Comment by ID
GET {{baseUrl}}/api/comments/{{commentId}}

###
